### ISSUE TITLE
Grab Azure custom-script stdout and stderr logs

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#21]
When executing the `logs-capture.yml` playbook, please grab the contents of the following directory, which is only viewable as `root` on the bootstrap VM. 

`/var/lib/waagent/custom-script/download/0/`

```
ls -l /var/lib/waagent/custom-script/download/0/
total 1348
-r-x------. 1 root root   16163 Aug  2 19:44 script.sh
-rw-------. 1 root root 1306963 Aug  2 21:04 stderr
-rw-------. 1 root root   52533 Aug  2 19:51 stdout
```

All three of the files above should be part of the data capture. 

Additionally, please rename `logs-capture.yml` to `must-gather.yml` as that is the IBM standardized name for any data capture that's needed for support.

**Comment by midhun6989** [comment]
@ivandov Please review the PR https://github.com/IBM/zmodstack-deploy/pull/23 raised with the changes.

**Comment by midhun6989** [comment]
Closing the issue as the changes are merged into `dev` branch.
