### ISSUE TITLE
Diagnostic Directory 

### ISSUE THREAD

**Issue by JerryMSFT** [IBM/zmodstack-deploy#35]
Diagnostic Directory does not exist under zmodstack-deploy/azure/ansible/diagnostic.

**Comment by midhun6989** [comment]
@JerryMSFT Latest changes are in `dev` branch only, and not yet promoted to `main` branch. So please clone the `dev` branch and proceed.
`git clone --branch dev https://github.com/IBM/zmodstack-deploy.git`

**Comment by midhun6989** [comment]
Issue faced by @JerryMSFT was due to insufficient quotas for CPU in the region where the deployment is tried. After increasing the CPU quota, able to successfully deploy the OCP Cluster. Thus, closing the issue.
