### ISSUE TITLE
Enable OpenShift Pipelines by default in all new AWS and Azure clusters

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#54]
### Description
As we continue to build out automation to run from within OCP as tekton tasks, we should enable OCP Pipelines by default.

### Potential Solutions
1. Check for a setting in the `install-config.yml` to enable during initial OCP installation
2. Install the Operator following the same process we've done with zmodstack operators

### Additional Context
- Part of the [Epic](https://github.com/IBM/zmodstack-deploy/issues/56)

**Comment by midhun6989** [comment]
@ivandov Could you confirm if it is fine to get the `OpenShift Pipelines Operator` installed in the OCP Cluster, similar to the installation of `IBM Operator Catalogue` as in [here](https://github.com/IBM/zmodstack-deploy/blob/dev/azure/scripts/ansible/playbooks/roles/ocpcluster/tasks/main.yml#L115-#L120)? A task to verify the successful installation of the operator can be added post this.
Or whether a new Ansible role has to be created in the `ocp` monorepo at [here](https://github.com/IBM/zmodstack-deploy/tree/dev/ocp/ansible/roles)?

**Comment by midhun6989** [comment]
@ivandov Please review the [PR](https://github.com/IBM/zmodstack-deploy/pull/95) for the changes.
1. Created an Ansilbe role `ocp-pipelines` for installing OpenShift Pipelines Operator
2. Created an Ansible role `ibm-op-cat` for setting up the IBM Operator Catalog

**Comment by midhun6989** [comment]
@nikita-hakari After getting approval for the [PR](https://github.com/IBM/zmodstack-deploy/pull/95);
1. UserData script in AWS will have to be modified to run the Ansible role `ocp-pipelines`
2. You may also refactor the Ansilbe role `ocp-install` and reuse the Ansible role `ibm-op-cat` for setting up the IBM Operator Catalog

**Comment by midhun6989** [comment]
Closing the issue as the changes are merged into `main` branch.
