### ISSUE TITLE
Allows failures in product automation playbooks

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#71]
### Description
When the `ocp/playbooks/main.yml` fails to install one of the product operators, we should allow failures on the installation and continue on to try the install of the next product.

Additionally, ensure that all playbook executions **always** respond with a success message, regardless of any failures to install products. This way Azure and AWS deployments are not considered failing if an issue is encountered during product deployments.

**Comment by midhun6989** [comment]
@ivandov Used `block`, `rescue` and `always` in Ansible playbook for error handling. [Reference](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html). Commit in `release-2023.4.1` branch is https://github.com/IBM/zmodstack-deploy/pull/75/commits/7833178e7d675f03a898beeb9d0ac87dd6ce5270. Please review

**Comment by ivandov** [comment]
Merged changes look good. Leaving open for another few days to explore if there are functional changes if we use `import_role` instead of `include_role`.

**Comment by ivandov** [comment]
Closing, looks good.
