### ISSUE TITLE
Update default OCP versions to 4.13 and allow 4.14 deployment

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#72]
### Description

When deploying OCP in AWS and Azure, we should set the default OCP version to `4.13` and allow the deployment of `4.14` clusters.

**Comment by nikita-hakari** [comment]
Updated for the AWS templates.

**Comment by midhun6989** [comment]
Azure Templates are updated.

**Comment by ivandov** [comment]
Updates have been merged to `dev` and release branches.
