### ISSUE TITLE
When running zoscb install, force a cluster-scoped install of the foundational services

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#73]
### Description

When installing zoscb, to ensure there's no cluster-scoped conflicts with the foundational services operator, we should force a cluster-scoped install of the foundational services operator prior to installing the zoscb operator.

This addition can be placed in the `zoscb` role.

**Comment by midhun6989** [comment]
@ivandov Made the changes in `release-2023.4.1` branch with commit https://github.com/IBM/zmodstack-deploy/pull/75/commits/f12b7e6f02b845fdc86917a0d491081d93b8e9ef. Please review.

**Comment by ivandov** [comment]
Merged changes look good, ty, closing!
