### ISSUE TITLE
Create domain delegation process

### ISSUE THREAD

**Issue by nikita-hakari** [IBM/zmodstack-deploy#81]
The domain delegation script used to create the domains during the AWS workshops which was user the alliance team should be moved under our zmodstack account. 
Create the required resources and set up the process

**Comment by nikita-hakari** [comment]
The process is set up.
This involved creation on api gateway 
lambda and their associated roles and policies

The domain delegation shell script is also developed and modified to use the new endpoint.

**Comment by ivandov** [comment]
AWS team plans to validate this functionality in the first few weeks of Jan.
